# Generated by Django 3.2.8 on 2021-10-29 14:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpreadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.CharField(max_length=255)),
                ('first_team', models.CharField(max_length=255)),
                ('second_team', models.CharField(max_length=255)),
                ('spread', models.IntegerField()),
                ('spreadIsPick', models.BooleanField()),
                ('start_datetime', models.DateTimeField()),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ticket', max_length=255)),
                ('pub_date', models.DateField(default=datetime.date.today, unique=True)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='TicketOrderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TicketPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=5)])),
                ('date', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sportsbetting.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='UnderOverEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255)),
                ('under', models.IntegerField()),
                ('over', models.IntegerField()),
                ('under_or_over', models.BooleanField(blank=True, null=True)),
                ('linked_spread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='under_over', to='sportsbetting.spreadentry')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_overs', to='sportsbetting.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='UnderOverPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_or_over', models.BooleanField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_over_picks', to='sportsbetting.ticketplay')),
                ('under_over_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='sportsbetting.underoverentry')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked', models.CharField(max_length=255)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spread_picks', to='sportsbetting.ticketplay')),
                ('spread_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='sportsbetting.spreadentry')),
            ],
        ),
        migrations.AddField(
            model_name='spreadentry',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='sportsbetting.ticket'),
        ),
        migrations.AddConstraint(
            model_name='underoverpick',
            constraint=models.UniqueConstraint(fields=('play', 'under_over_entry'), name='unique_under_over_pick'),
        ),
        migrations.AddConstraint(
            model_name='spreadpick',
            constraint=models.UniqueConstraint(fields=('play', 'spread_entry'), name='unique_spread_pick'),
        ),
    ]
