# Generated by Django 3.2.8 on 2021-10-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='spreadentry',
            name='isPreview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spreadentry',
            name='spread',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadentry',
            name='spreadIsPick',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='underoverentry',
            name='over',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='underoverentry',
            name='under',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TM', 'Team'), ('PL', 'Player')], default='TM', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(blank=True, max_length=32, null=True)),
                ('member_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sportsbetting.participant')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sportsbetting.sport')),
            ],
        ),
    ]
