# Generated by Django 5.1.4 on 2025-02-26 22:17

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("sportsbetting", "0002_sport_banner"),
	]

	operations = [
		migrations.AlterField(
			model_name="scheduledgame",
			name="away_team",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="scheduled_games_away_team",
				to="sportsbetting.team",
			),
		),
		migrations.AlterField(
			model_name="scheduledgame",
			name="home_team",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="scheduled_games_home_team",
				to="sportsbetting.team",
			),
		),
		migrations.AlterField(
			model_name="scheduledgame",
			name="league",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="scheduled_games",
				to="sportsbetting.league",
			),
		),
		migrations.AlterField(
			model_name="scheduledgame",
			name="sport",
			field=auto_prefetch.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="scheduled_games",
				to="sportsbetting.sport",
			),
		),
	]
