# Generated by Django 3.2.8 on 2021-10-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbetting', '0002_auto_20211029_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='underoverentry',
            name='game',
        ),
        migrations.AddField(
            model_name='sport',
            name='short',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='spreadentry',
            name='sport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='sportsbetting.sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='sports',
            field=models.ManyToManyField(related_name='on_tickets', to='sportsbetting.Sport'),
        ),
        migrations.AlterField(
            model_name='spreadentry',
            name='gametype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
