# Generated by Django 5.2.1 on 2025-06-27 17:46

import auto_prefetch
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import sportsbetting.models


class Migration(migrations.Migration):
	dependencies = [
		("sportsbetting", "0002_populate_sports_and_bodies"),
	]

	operations = [
		migrations.RemoveConstraint(
			model_name="team",
			name="unique_team_per_league",
		),
		migrations.RemoveField(
			model_name="game",
			name="sport",
		),
		migrations.AddField(
			model_name="game",
			name="boxscore",
			field=models.CharField(editable=False, max_length=100, null=True),
		),
		migrations.AddField(
			model_name="play",
			name="status",
			field=models.CharField(
				blank=True,
				help_text="Status of the play, e.g., 'pending', 'completed'",
				max_length=50,
				null=True,
			),
		),
		migrations.AlterField(
			model_name="bettingline",
			name="game",
			field=auto_prefetch.OneToOneField(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="betting_line",
				to="sportsbetting.game",
			),
		),
		migrations.AlterField(
			model_name="team",
			name="brand",
			field=models.ImageField(
				blank=True,
				null=True,
				upload_to=sportsbetting.models.save_uploaded_brands,
			),
		),
		migrations.AlterField(
			model_name="team",
			name="logo",
			field=models.ImageField(
				blank=True,
				null=True,
				upload_to=sportsbetting.models.save_uploaded_logos,
			),
		),
		migrations.AddConstraint(
			model_name="game",
			constraint=models.UniqueConstraint(
				condition=models.Q(("boxscore__isnull", False)),
				fields=("boxscore",),
				name="unique_game_boxscore_when_not_null",
			),
		),
		migrations.AddConstraint(
			model_name="team",
			constraint=models.UniqueConstraint(
				django.db.models.functions.text.Lower("name"),
				models.F("league"),
				name="unique_team_per_league",
			),
		),
	]
