# Generated by Django 3.2.8 on 2021-10-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('sportsbetting', '0003_auto_20211030_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorderpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='spreadentry',
            name='gametype',
        ),
        migrations.DeleteModel(
            name='SportsPage',
        ),
        migrations.DeleteModel(
            name='TicketOrderPage',
        ),
    ]
