# Generated by Django 5.2.1 on 2025-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		(
			"sportsbetting",
			"0003_play_status_alter_bettingline_game_alter_team_brand_and_more",
		),
	]

	operations = [
		migrations.RemoveField(
			model_name="game",
			name="sport",
		),
		migrations.AddField(
			model_name="game",
			name="boxscore",
			field=models.CharField(editable=False, max_length=100, null=True),
		),
		migrations.AddConstraint(
			model_name="game",
			constraint=models.UniqueConstraint(
				condition=models.Q(("boxscore__isnull", False)),
				fields=("boxscore",),
				name="unique_game_boxscore_when_not_null",
			),
		),
	]
