# Generated by Django 5.2.1 on 2025-06-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		(
			"sportsbetting",
			"0003_remove_team_unique_team_per_league_remove_game_sport_and_more",
		),
	]

	operations = [
		migrations.AlterField(
			model_name="play",
			name="status",
			field=models.CharField(
				blank=True,
				choices=[("p", "Pending"), ("c", "Completed")],
				help_text="Status of the play, e.g., 'pending', 'completed'",
				max_length=1,
				null=True,
			),
		),
	]
