# Generated by Django 5.2.1 on 2025-08-09 19:21

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("sportsbetting", "0005_play_stakes_currency_alter_play_stakes"),
	]

	operations = [
		migrations.AlterModelOptions(
			name="play",
			options={
				"base_manager_name": "prefetch_manager",
				"verbose_name": "bet slip",
				"verbose_name_plural": "bet slips",
			},
		),
	]
