# Generated by Django 3.2.8 on 2021-10-29 14:25

import django.db.models.deletion
import wagtail.core.fields
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		("wagtailcore", "0062_comment_models_and_pagesubscription"),
		("wagtailimages", "0023_add_choose_permissions"),
	]

	operations = [
		migrations.CreateModel(
			name="SportsbookLoginPage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
				(
					"background",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="wagtailimages.image",
					),
				),
				(
					"search_image",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="wagtailimages.image",
						verbose_name="Search image",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=(
				wagtailmetadata.models.WagtailImageMetadataMixin,
				"wagtailcore.page",
				models.Model,
			),
		),
		migrations.CreateModel(
			name="HomePage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
				("body", wagtail.core.fields.RichTextField(blank=True)),
				(
					"background",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="wagtailimages.image",
					),
				),
				(
					"search_image",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="wagtailimages.image",
						verbose_name="Search image",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=(
				wagtailmetadata.models.WagtailImageMetadataMixin,
				"wagtailcore.page",
				models.Model,
			),
		),
		migrations.CreateModel(
			name="GenericPage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
				("body", wagtail.core.fields.RichTextField(blank=True)),
				(
					"background",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="wagtailimages.image",
					),
				),
				(
					"search_image",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="wagtailimages.image",
						verbose_name="Search image",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=(
				wagtailmetadata.models.WagtailImageMetadataMixin,
				"wagtailcore.page",
				models.Model,
			),
		),
	]
