# Generated by Django 5.2.9 on 2026-01-04 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("gameonlock", "0001_initial"),
		("wagtail_newsletter", "0001_initial"),
		("wagtailcore", "0095_query_searchpromotion_querydailyhits"),
	]

	operations = [
		migrations.CreateModel(
			name="NewsletterIndexPage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=("wagtailcore.page",),
		),
		migrations.CreateModel(
			name="MonthlyDigestPage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
				(
					"newsletter_subject",
					models.CharField(
						blank=True,
						help_text="Subject for the newsletter. Defaults to page title if blank.",
						max_length=1000,
					),
				),
				("newsletter_campaign", models.CharField(blank=True, max_length=1000)),
				("month", models.PositiveSmallIntegerField()),
				("year", models.PositiveSmallIntegerField()),
				("compiled_html", models.TextField(blank=True, editable=False)),
				(
					"newsletter_recipients",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						to="wagtail_newsletter.newsletterrecipients",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=("wagtailcore.page",),
		),
	]
