# Generated by Django 5.1.4 on 2025-05-02 15:10

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameonlock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=localflavor.us.models.USStateField(
                blank=True, max_length=2, verbose_name="state"
            ),
        ),
    ]
