# Generated by Django 5.2.3 on 2025-09-21 19:30

import django.db.models.deletion
import wagtail.fields
import wagtailmetadata.models
from django.db import migrations, models

import gameonlock.views.mixins
import sportsbetting.views.mixins


class Migration(migrations.Migration):
	dependencies = [
		("gameonlock", "0001_initial"),
		("wagtail_newsletter", "0001_initial"),
		("wagtailcore", "0095_query_searchpromotion_querydailyhits"),
		("wagtailimages", "0027_image_description"),
	]

	operations = [
		migrations.CreateModel(
			name="NewsletterIndexPage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=("wagtailcore.page",),
		),
		migrations.CreateModel(
			name="HomePage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
				(
					"about_title",
					models.CharField(blank=True, default="About us", max_length=255),
				),
				(
					"about_subtitle",
					models.CharField(
						blank=True,
						default="We provide the most reliable & legal betting",
						max_length=255,
					),
				),
				("about_content", wagtail.fields.RichTextField(blank=True, default="")),
				(
					"bet_title",
					models.CharField(
						blank=True, default="Available Bets", max_length=255
					),
				),
				(
					"bet_subtitle",
					models.CharField(
						blank=True,
						default="Choose Your Match & Place A Bet",
						max_length=255,
					),
				),
				(
					"schedule_title",
					models.CharField(
						blank=True, default="Next Schedule", max_length=255
					),
				),
				(
					"schedule_subtitle",
					models.CharField(
						blank=True, default="All Upcoming Matches", max_length=255
					),
				),
				(
					"search_image",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="+",
						to="wagtailimages.image",
						verbose_name="Search image",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=(
				sportsbetting.views.mixins.SportsBettingContextMixin,
				gameonlock.views.mixins.GameonlockMixin,
				wagtailmetadata.models.WagtailImageMetadataMixin,
				"wagtailcore.page",
				models.Model,
			),
		),
		migrations.CreateModel(
			name="MonthlyDigestPage",
			fields=[
				(
					"page_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to="wagtailcore.page",
					),
				),
				(
					"newsletter_subject",
					models.CharField(
						blank=True,
						help_text="Subject for the newsletter. Defaults to page title if blank.",
						max_length=1000,
					),
				),
				("newsletter_campaign", models.CharField(blank=True, max_length=1000)),
				("month", models.PositiveSmallIntegerField()),
				("year", models.PositiveSmallIntegerField()),
				("compiled_html", models.TextField(blank=True, editable=False)),
				(
					"newsletter_recipients",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						to="wagtail_newsletter.newsletterrecipients",
					),
				),
			],
			options={
				"abstract": False,
			},
			bases=("wagtailcore.page",),
		),
	]
