# Generated by Django 5.2.1 on 2025-06-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("gameonlock", "0001_initial"),
	]

	operations = [
		migrations.AddField(
			model_name="user",
			name="referral_id",
			field=models.CharField(blank=True, max_length=12, null=True, unique=True),
		),
		migrations.AddField(
			model_name="user",
			name="referred_by",
			field=models.CharField(blank=True, max_length=12, null=True),
		),
	]
