# Generated by Django 3.2.8 on 2021-10-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("ecommerce_app", "0001_initial"),
	]

	operations = [
		migrations.AlterField(
			model_name="cartitem",
			name="id",
			field=models.BigAutoField(
				auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
			),
		),
		migrations.AlterField(
			model_name="lineitem",
			name="id",
			field=models.BigAutoField(
				auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
			),
		),
		migrations.AlterField(
			model_name="order",
			name="id",
			field=models.BigAutoField(
				auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
			),
		),
		migrations.AlterField(
			model_name="product",
			name="id",
			field=models.BigAutoField(
				auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
			),
		),
	]
