# Generated by Django 5.2.1 on 2025-08-09 19:21

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		(
			"golpayment",
			"0002_rename_date_time_transaction_transaction_datetime_and_more",
		),
	]

	operations = [
		migrations.RemoveField(
			model_name="transaction",
			name="status",
		),
		migrations.AddField(
			model_name="transaction",
			name="method",
			field=models.CharField(
				choices=[("pp", "PayPal")],
				default="pp",
				help_text="Method of transaction",
				max_length=2,
				verbose_name="gateway",
			),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name="transaction",
			name="amount",
			field=djmoney.models.fields.MoneyField(
				decimal_places=2,
				default_currency="USD",
				help_text="Transaction amount",
				max_digits=10,
				verbose_name="amount",
			),
		),
		migrations.AlterField(
			model_name="transaction",
			name="transaction_datetime",
			field=models.DateTimeField(
				help_text="Date and time of the transaction", verbose_name="date"
			),
		),
		migrations.AlterField(
			model_name="transaction",
			name="transaction_id",
			field=models.CharField(
				help_text="Unique identifier for the transaction",
				max_length=100,
				unique=True,
				verbose_name="trnx ID",
			),
		),
		migrations.AlterField(
			model_name="transaction",
			name="type",
			field=models.CharField(
				choices=[("d", "Deposit"), ("w", "Withdraw")],
				help_text="Type of transaction",
				max_length=1,
				verbose_name="type",
			),
		),
	]
