# Generated by Django 3.2.8 on 2021-12-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211029_0936'),
        ('blog', '0003_auto_20211029_0952'),
    ]

    operations = [
    ]
