# Generated by Django 5.2.9 on 2026-01-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("puput", "0001_initial"),
		("wagtailimages", "0027_image_description"),
	]

	operations = [
		migrations.AddField(
			model_name="blogpage",
			name="search_image",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="+",
				to="wagtailimages.image",
				verbose_name="Search image",
			),
		),
		migrations.AddField(
			model_name="entrypage",
			name="search_image",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="+",
				to="wagtailimages.image",
				verbose_name="Search image",
			),
		),
	]
