name: CI

on:
  push:
    branches: [ openhands ]
  pull_request:
    branches: [ openhands ]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff isort djlint
      - name: Ruff check and fix
        run: ruff check --fix .
      - name: isort
        run: isort .
      - name: Ruff format
        run: ruff format .
      - name: Djlint reformat templates
        run: djlint --reformat templates/
      - name: Commit and push changes
        run: |
          git config --global user.name 'Naggafin'
          git config --global user.email 'nevincoutu@gmail.com'
          git add .
          git diff --cached --quiet || git commit -m 'ci: auto-format and lint fixes'
          git push || echo 'No changes to push.'
  test:
    runs-on: ubuntu-latest
    needs: lint-format
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django
      - name: Run tests
        env:
          DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
        run: pytest tests/
